### ISSUE TITLE
Question: Strategy for Latest Context between two types: `fdc3.instrument` and `fdc3.instrumentList` while ignoring others

### ISSUE THREAD

**Issue by Bruno-LSEG** [finos/FDC3#1616]
### Question Area
 - [ ] App Directory
 - [ ] API
 - [x] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question
Many of the apps in our suite handle both `fdc3.instrument` and `fdc3.instrumentList` and currently it's unclear how an app joining a channel with context data available can get the "latest" between two types, while ignoring other context types. 

```
Three apps — A, B and C:
App A and App B joins user channel 1
App A broadcasts an fdc3.instrument context
App B broadcasts an fdc3.instrumentList context
App A broadcasts and fdc3.contact context
App C joins user channel 1
App C adds a context listener (using fdc3.addContextListener(null, callback) )
```

Is there a way to determine which one is the most recent context between instrument and instrumentList?

**Comment by kriswest** [comment]
If you add a `null` typed context listener to a user channel, you'll receive the most recent context (of any type) immediately - so checking its type will tell you. If you add a typed listener, you'll get the most recent context of that type instead - you can also manually retrieve those types with `channel.getCurrentContext`.

If you needed the most recent type + the most recent context of each type you could do this in app C:

```js
await fdc3.addContextListener(null, handler); //will receive most recent type
const currentChannel = await fdc3.getCurrentChannel();
const lastestInstrument = null, latestinstumentList = null;
if (currentChannel) {
    latestInstrument = await channel.getCurrentContext("fdc3.instrument");
    latestInstrumentList = await channel.getCurrentContext("fdc3.instrumentList");
}
```
I'd do it that way rather than adding 3 different listeners as I'm assuming you want a single listener to handle all types, and through that to know which was most recent.

Does that help?

**Comment by kriswest** [comment]
@Bruno-LSEG yes `fdc3.getCurrentContext(someType)` doesn't tell you what was most recent, just the most recent of that type. However, `fdc3.getCurrentContext(null)` should give you the latest of any type, as will just adding a context listener with a null type with `fdc3.addContextListener(null, handler);`. 

Its worth noting that *app* channel listeners do NOT give you the latest context (i.e. `const chan = await fdc3.getCurrentChannel(); chan.addContextListener(null, handler)).` behaves differently to `àwait fdc3.addContextListener(null, handler)`.

> [The Standard says that a context listener for null should return the latest context regardless of type](https://fdc3.finos.org/docs/api/ref/DesktopAgent#addcontextlistener:~:text=If%20null%20was%20passed%20as%20the%20context%20type%20for%20the%20listener%20and%20the%20channel%20contains%20context%2C%20then%20the%20handler%20function%20will%20be%20called%20immediately%20with%20the%20most%20recent%20context%20%2D%20regardless%20of%20type.), but does that mean only the latest should get sent or all types ordered by most recent?

Only the most recent context (of the specified type or any type if `null` was specified. If your handler is being passed anything other than a single context object, then the DA implementation is not conformant to the Standard.

> In the below screenshot we can observe that when you broadcast a context type the first time, it gets added to some internal dictionary in the order they were first sent.
> 
> But broadcasting the same type a second time , makes no difference to the output.

That will be a map internal to the FDC3 client used to cache the most recent context of each type so that it can handle queries for the most recent message of each type. There will also be a flag, timestamp or duplicate tracking which was the most recent of any type.

> We are trying to evaluate if this is a gap in the Standard or a bug in the Desktop Agent implementation.

From what you've said I _think_ your DA is working correctly according to the standard. the FDC3 API doesn't give you back an ordered list of the latest contexts, it will only give you the latest of each type and of any type. If you need something more than that, please outline the use case or problem you are tying to solve and I'll see if i can suggest something.

**Comment by Bruno-LSEG** [comment]
Thanks for the clarification @kriswest.

What we are aiming for is making sure we can offer a consistent user experience, imagine this scenario:

The user selects multiple instruments from a `portfolio view app`, broadcasting an `fdc3.instrumentList` with, for example, 15 instruments. 

A `news app` picks that up and shows the list. The user then clicks on an individual entry within the news app, broadcasting an `fdc3.instrument`. 
Now all the apps in the screen are showing that single `fdc3.instrument` since they all are on the channel.

Finally, the user opens a `chart app` and joins it to the channel. The chart displays 15 lines in it, one for each of the instruments in the `fdc3.instrumentList` (which is now "stale"). The user has to click on the single instrument again to bring the `chart app` back to a synced state with the rest of the platform.

It would be very useful if the standard could encourage or enforce some form of ordering in the context types sent to an app joining a channel.

That way, in our example, the `Chart App` would know how to differentiate which context is latest and could show the user the appropriate data the first time.

**Comment by kriswest** [comment]
@Bruno-LSEG does the above help? I strongly suspect that the number and order of listeners that you add is what's causing the issue that your dealing with. Please close this issue if you're all set - otherwise I'd be happy to bring this into a meeting to address further.

**Comment by julianna-ciq** [comment]
This could also be solved by my proposal, #1290 . This involves sharing metadata along with contexts, which includes the `timestamp` of when a context was raised. If a firm wants to determine whether an `fdc3.instrument` or `fdc3.instrumentList` context was called first, they would be able to look at that context's originating timestamp. That is, once #1290 was adopted.

**Comment by openfin-johans** [comment]
I also assumed that getCurrentContext would solve this but in a situation where the current context is something not supported by your app eg an fdc3.contact in the example above - you would not be able to tell which of the fdc3.instrument or fdc3.instrumentList was actually the latest sent...

So, I think the request for an ordered list to be retuned when adding a context listener for the null type makes sense. Yes, if originating timestamp was included you could compare those but perhaps it's easier and/or cleaner to just go through the list and pick the first or last context type that your app support. Perhaps the first in the list should be latest so that you don't need to process more than necessary?

@Bruno-LSEG - please let us know if this would solve your need?

**Comment by kriswest** [comment]
> I also assumed that getCurrentContext would solve this but in a situation where the current context is something not supported by your app eg an fdc3.contact in the example above - you would not be able to tell which of the fdc3.instrument or fdc3.instrumentList was actually the latest sent...

This is not the case. Both `fdc3.addColntextListener(null)` and `fdc3.getCurrentContext(null)` are required to return you the latest context of any type. This is tested as part of the conformance tests for Desktop Agents and any agent that doesn't respond correctly fails that test.

At present this issue does not clearly articulate a problem that is not solved by the current API standard. None of the examples demonstrate how listeners are being added to the app and how it is being mislead as to the most recent context on the channel. These are some of the oldest API calls and most core use cases for FDC3 and have been used by apps to display the most recent context (potentially from a number of types) for many years.

The change @julianna-ciq flags will provide an alternative way for you to look at this data, if adopted and implemented, in future. However, the use case described is already supported in current versions of FDC3 and is used successfully in many applications.

@Bruno-LSEG If you post an example of how you are adding listeners the community will be able to provide support on where its going wrong or should be adapted. Otherwise, I believe this issue should be closed as multiple strategies are already provided.

**Comment by lspiro-Tick42** [comment]
It is worth noting that the implied 'equivalence' between an Instrument context and an Instrument List context, in the original question from Bruno-LSEG, is an application level decision. So I think just adding a timestamp to each typed context allows applications to decide how to interpret the Desktop Agent context i.e. the Dictionary of Context Types available when an application instance connects to a channel.

**Comment by Bruno-LSEG** [comment]
Hi @kriswest , i don't believe retaining the whole history of contexts is the way to go. We just need to have the `fdc3.addContextListener(null)` invoking the callback in an _ordered_ manner, the order being based on when each context type was last sent.

The example from @openfin-johans is simple and shows the situation quite clearly.

So from @openfin-johans 's example, App C would add a context listener for 
```
fdc3.addContextListener(null (c) => {
   if(c.type === 'fdc3.instrument' || c.type === 'fdc3.instrumentList') {
      debounceEager(c, (c) => workflowLogic(c));
   }
});
```

 and the order of callbacks would be: 

```
contact
instrumentList
instrument
```

That way AppC would take the first accepted context it receives and ignore the others for the duration of the debounce.

We cannot rely on calling `fdc3.getCurrentContext()` due to having many different context types flowing in the platform and not all apps support all context types or execute the same logic for all context types.

I have updated the title and description to be more factual.

**Comment by kriswest** [comment]
@Bruno-LSEG `fdc3.addContextListener(null, handler)` is already ordered in that it is called for the last context of any type only. What I think you are asking for is for it to be called for every current type on the channel. That's not likely appropriate for every application and would be a hefty, likely breaking change in behaviour for existing apps. Thats very likely to lead to a flickering effect in some apps as they re-render multiple times on receiving those callbacks in quick succession. Requiring every app to the debounce those calls adds complexity for every app and would require a major revision to FDC3 version numbering to do (as its not an addition to functionality, but a change to existing functionality).

> We cannot rely on calling fdc3.getCurrentContext() due to having many different context types flowing in the platform and not all apps support all context types or execute the same logic for all context types.

You'd only need to call `getCurrentContext(type)` for types that you support (I'm not propose you call it with a null type, rather call it for each type you want to know about). In fact, I think you are identifying an issue with what you propose for `fdc3.addContextListener(null, handler)` - the handler will get called for every type including those you don't support, without you knowing in advance how many times its going to get called. Whereas with `channel.getCurrentContext(type)` you know what types you are getting and exactly how many calls you are making, exactly what logic you will apply to each. However, you also need the timestamp info to get the ordering - which again is likely to be a breaking change to the return type.

That makes our options (at least in my opinion): 
1) Triggering an FDC3 3.0 release with a breaking solution.
2) Creating something new (e.g. a `channel.getAllCurrentContext`, with a return type that includes the metadata).

@julianna-ciq we probably need to think about the channel.getCurrentContext issue for metadata anyway...
